import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { shareApi, type SharedResume } from "../apis/share";

export function ShareView() {
  const { token } = useParams<{ token: string }>();
  const [resume, setResume] = useState<SharedResume | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showLatex, setShowLatex] = useState(false);
  const [iframeUrl, setIframeUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!resume || !resume.pdf_url) {
      setIframeUrl(null);
      return;
    }

    const pdfUrl = resume.pdf_url;
    if (pdfUrl.startsWith("data:application/pdf;base64,")) {
      try {
        const base64Data = pdfUrl.split(",")[1];
        const binaryString = atob(base64Data);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }
        const blob = new Blob([bytes], { type: "application/pdf" });
        const url = URL.createObjectURL(blob);
        setIframeUrl(`${url}#toolbar=0`);

        return () => {
          URL.revokeObjectURL(url);
        };
      } catch (e) {
        console.error("Failed to parse base64 PDF in ShareView:", e);
        setIframeUrl(pdfUrl);
      }
    } else {
      setIframeUrl(`${pdfUrl}#toolbar=0`);
    }
  }, [resume]);

  useEffect(() => {
    if (!token) return;
    shareApi
      .get(token)
      .then(setResume)
      .catch((err) => setError(err.message || "Failed to load shared resume"))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-100 font-sans">
        <p className="text-gray-500">Loading shared resume...</p>
      </div>
    );
  }

  if (error || !resume) {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-100 font-sans">
        <p className="text-red-500">{error || "Resume not found"}</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col bg-gray-100 font-sans">
      <header className="bg-white border-b px-6 py-4 flex items-center justify-between">
        <h1 className="text-xl font-bold tracking-tight">
          ResumeReworker{" "}
          <span className="font-normal text-gray-500">Shared Preview</span>
        </h1>
        <div className="flex gap-4">
          <button
            onClick={() => setShowLatex(!showLatex)}
            className="px-4 py-2 text-sm font-medium border rounded-md hover:bg-gray-50 transition-colors"
          >
            {showLatex ? "Hide LaTeX Source" : "View LaTeX Source"}
          </button>
        </div>
      </header>

      <main className="flex-1 flex overflow-hidden">
        {showLatex && (
          <div className="w-1/2 border-r bg-white overflow-y-auto p-4 font-mono text-sm">
            <pre className="whitespace-pre-wrap">{resume.tex_source}</pre>
          </div>
        )}
        <div
          className={`flex-1 bg-gray-200 overflow-hidden ${!showLatex && "w-full"}`}
        >
          {iframeUrl ? (
            <iframe
              src={iframeUrl}
              className="w-full h-full"
              title="Resume Preview"
            />
          ) : (
            <div className="flex items-center justify-center h-full text-gray-500">
              PDF preview not available
            </div>
          )}
        </div>
      </main>
      <footer className="bg-white border-t px-6 py-2 text-xs text-gray-400 flex justify-between">
        <span>Anonymized and generated by ResumeReworker</span>
        <span>Views: {resume.view_count}</span>
      </footer>
    </div>
  );
}
